import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'fr' | 'ar';

export const TRANSLATIONS = {
  en: {
    nav_home: "Home",
    nav_parts: "Parts Catalogue",
    nav_contact: "Contact",
    nav_call: "Call Us",
    hero_badge: "Opel & Ford Parts Specialist — Sousse",
    hero_title_parts: "AUTO PARTS",
    hero_title_prefix: "GENUINE & HIGH-QUALITY",
    hero_subtitle: "Your premium source for Opel and Ford components. From engine and brake kits to suspension and lubricants. Excellent quality, fair pricing, and expert guidance.",
    hero_stat_parts: "Parts Catalogued",
    hero_stat_models: "Car Models Covered",
    hero_stat_quality: "Quality Inspected",
    hero_btn_browse: "Browse Parts Catalogue",
    hero_btn_contact: "Contact Us",
    hero_btn_call: "Call Shop",
    brand_section_title: "Select Your Vehicle Brand",
    brand_section_subtitle: "Find exact matching parts designed specifically for your model's architecture.",
    brand_opel_desc: "Compatible with Astra G & H, Corsa C, and Vectra B models.",
    brand_ford_desc: "Compatible with Focus Mk1 & Mk2, Fiesta Mk5, and Mondeo Mk3 models.",
    brand_explore_opel: "Explore Opel Catalog →",
    brand_explore_ford: "Explore Ford Catalog →",
    featured_parts_title: "Featured Parts in Stock",
    featured_parts_subtitle: "High-demand parts available for immediate pickup or delivery in Sousse.",
    featured_btn_all: "Browse All 100+ Parts",
    why_us_title: "Why Choose STE SAKJI",
    why_us_subtitle: "Committed to providing premium parts, transparent pricing, and excellent service in Sousse.",
    why_us_01_title: "Genuine Quality",
    why_us_01_desc: "We stock only genuine OEM parts and premium components that are fully tested and certified.",
    why_us_02_title: "Local Convenience",
    why_us_02_desc: "Located in Sousse (Rue de l'Abreuvoir), we offer immediate collection or rapid local distribution.",
    why_us_03_title: "Expert Advice",
    why_us_03_desc: "Need compatibility verification? Our team will verify fitment against your chassis or part number.",
    testimonials_title: "What Our Clients Say",
    testimonials_subtitle: "Honest reviews from Opel & Ford owners who source their parts from us.",
    cta_title: "Looking for a specific part?",
    cta_subtitle: "Visit our shop in Sousse or check our catalogue for real-time stock availability.",
    cta_btn_contact: "Visit Our Shop",
    cta_btn_call: "Call +216 98 228 469",
    cta_btn_browse: "Browse Catalogue",
    footer_tagline: "Professional auto parts shop for Opel and Ford vehicles. Genuine OEM parts in Sousse, Tunisia.",
    footer_quick_links: "Quick Links",
    footer_contact_hours: "Contact & Hours",
    footer_address: "RJCR+M9G, Rue de l'Abreuvoir, Sousse",
    footer_rights: "STE SAKJI AutoShop. All rights reserved.",
    hours_mon_fri: "Mon – Fri:",
    hours_sat: "Saturday:",
    hours_sun: "Sunday:",
    hours_closed: "Closed",
    parts_header_title: "Parts Catalogue",
    parts_header_subtitle: "Browse our extensive catalogue of 100+ high-quality OEM parts for Opel and Ford models.",
    parts_search_placeholder: "Search by part name, OEM number, model...",
    parts_filter_brand: "Brand",
    parts_filter_model: "Model",
    parts_filter_category: "Category",
    parts_filter_manufacturer: "Manufacturer",
    parts_filter_condition: "Condition",
    parts_condition_all: "All Conditions",
    parts_condition_new: "New",
    parts_condition_reconditioned: "Reconditioned",
    parts_showing: "Showing",
    parts_count_parts: "parts",
    parts_clear_filters: "Clear Filters",
    parts_view_details: "View Details",
    parts_price: "Price",
    parts_stock_status: "Stock Status",
    parts_stock_in: "In Stock",
    parts_stock_low: "Low Stock",
    parts_stock_out: "Out of Stock",
    parts_empty_title: "No parts matched your search",
    parts_empty_desc: "Try resetting the filters or searching for something else.",
    parts_empty_btn: "Clear All Filters",
    parts_brand: "Brand",
    parts_model: "Model",
    parts_category: "Category",
    parts_manufacturer: "Manufacturer",
    parts_oem: "OEM Number",
    parts_year: "Year Range",
    detail_back: "← Back to Catalogue",
    detail_compatible_models: "Compatible Models",
    detail_specifications: "Specifications",
    detail_part_number: "Part Number (OEM)",
    detail_brand: "Vehicle Brand",
    detail_condition: "Condition",
    detail_category: "Category",
    detail_manufacturer: "Manufacturer",
    detail_year_range: "Year Range",
    detail_stock_qty: "Stock Quantity",
    detail_unit_price: "Unit Price",
    detail_order_instructions: "How to Order",
    detail_order_desc: "To order this part, please visit our shop in Sousse or contact us with the OEM Part Number. We will verify the chassis compatibility and prepare the part for you.",
    detail_call_now: "Call +216 98 228 469 to Order",
    detail_visit_shop: "Visit shop at Rue de l'Abreuvoir, Sousse",
  },
  fr: {
    nav_home: "Accueil",
    nav_parts: "Catalogue de pièces",
    nav_contact: "Contact",
    nav_call: "Appelez-nous",
    hero_badge: "Spécialiste des pièces Opel & Ford — Sousse",
    hero_title_parts: "PIÈCES AUTO",
    hero_title_prefix: "D'ORIGINE & DE QUALITÉ",
    hero_subtitle: "Votre source de choix pour les composants Opel et Ford. Des kits de distribution et de freinage aux suspensions et lubrifiants. Excellente qualité, prix justes et conseils d'experts.",
    hero_stat_parts: "Pièces Cataloguées",
    hero_stat_models: "Modèles Couverts",
    hero_stat_quality: "Qualité Inspectée",
    hero_btn_browse: "Parcourir le catalogue",
    hero_btn_contact: "Nous Contacter",
    hero_btn_call: "Appeler le magasin",
    brand_section_title: "Sélectionnez la marque de votre véhicule",
    brand_section_subtitle: "Trouvez les pièces exactes conçues spécifiquement pour l'architecture de votre modèle.",
    brand_opel_desc: "Compatible avec les modèles Astra G & H, Corsa C et Vectra B.",
    brand_ford_desc: "Compatible avec les modèles Focus Mk1 & Mk2, Fiesta Mk5 et Mondeo Mk3.",
    brand_explore_opel: "Explorer le catalogue Opel →",
    brand_explore_ford: "Explorer le catalogue Ford →",
    featured_parts_title: "Pièces en vedette en stock",
    featured_parts_subtitle: "Pièces à forte demande disponibles pour ramassage immédiat ou livraison à Sousse.",
    featured_btn_all: "Parcourir plus de 100 pièces",
    why_us_title: "Pourquoi choisir STE SAKJI",
    why_us_subtitle: "Engagé à fournir des pièces de qualité, des prix transparents et un excellent service à Sousse.",
    why_us_01_title: "Qualité d'origine",
    why_us_01_desc: "Nous ne stockons que des pièces d'origine OEM et des composants de qualité supérieure entièrement testés.",
    why_us_02_title: "Praticité locale",
    why_us_02_desc: "Situé à Sousse (Rue de l'Abreuvoir), nous proposons un retrait immédiat ou une distribution locale rapide.",
    why_us_03_title: "Conseils d'experts",
    why_us_03_desc: "Besoin d'une vérification de compatibilité ? Appelez notre équipe pour valider le montage par rapport à votre châssis.",
    testimonials_title: "Ce que disent nos clients",
    testimonials_subtitle: "Avis honnêtes des propriétaires d'Opel & Ford qui s'approvisionnent chez nous.",
    cta_title: "Vous recherchez une pièce spécifique ?",
    cta_subtitle: "Visitez notre magasin à Sousse ou consultez notre catalogue pour voir les stocks disponibles.",
    cta_btn_contact: "Visiter notre magasin",
    cta_btn_call: "Appeler +216 98 228 469",
    cta_btn_browse: "Parcourir le catalogue",
    footer_tagline: "Magasin de pièces auto professionnel pour Opel et Ford. Pièces d'origine OEM à Sousse, Tunisie.",
    footer_quick_links: "Liens rapides",
    footer_contact_hours: "Contact & Horaires",
    footer_address: "RJCR+M9G, Rue de l'Abreuvoir, Sousse",
    footer_rights: "STE SAKJI AutoShop. Tous droits réservés.",
    hours_mon_fri: "Lun – Ven :",
    hours_sat: "Samedi :",
    hours_sun: "Dimanche :",
    hours_closed: "Fermé",
    parts_header_title: "Catalogue de pièces",
    parts_header_subtitle: "Parcourez notre vaste catalogue de plus de 100 pièces d'origine de haute qualité pour les modèles Opel et Ford.",
    parts_search_placeholder: "Rechercher par nom de pièce, numéro OEM, modèle...",
    parts_filter_brand: "Marque",
    parts_filter_model: "Modèle",
    parts_filter_category: "Catégorie",
    parts_filter_manufacturer: "Fabricant",
    parts_filter_condition: "État",
    parts_condition_all: "Tous les états",
    parts_condition_new: "Neuf",
    parts_condition_reconditioned: "Reconditionné",
    parts_showing: "Affichage de",
    parts_count_parts: "pièces",
    parts_clear_filters: "Effacer les filtres",
    parts_view_details: "Voir les détails",
    parts_price: "Prix",
    parts_stock_status: "Statut du stock",
    parts_stock_in: "En Stock",
    parts_stock_low: "Stock Faible",
    parts_stock_out: "Rupture de Stock",
    parts_empty_title: "Aucune pièce ne correspond à votre recherche",
    parts_empty_desc: "Essayez de réinitialiser les filtres ou de rechercher autre chose.",
    parts_empty_btn: "Effacer tous les filtres",
    parts_brand: "Marque",
    parts_model: "Modèle",
    parts_category: "Catégorie",
    parts_manufacturer: "Fabricant",
    parts_oem: "Numéro OEM",
    parts_year: "Années",
    detail_back: "← Retour au catalogue",
    detail_compatible_models: "Modèles compatibles",
    detail_specifications: "Spécifications",
    detail_part_number: "Numéro de pièce (OEM)",
    detail_brand: "Marque du véhicule",
    detail_condition: "État",
    detail_category: "Catégorie",
    detail_manufacturer: "Fabricant",
    detail_year_range: "Années de compatibilité",
    detail_stock_qty: "Quantité en stock",
    detail_unit_price: "Prix unitaire",
    detail_order_instructions: "Comment commander",
    detail_order_desc: "Pour commander cette pièce, veuillez visiter notre magasin à Sousse ou nous contacter avec le numéro de pièce OEM. Nous vérifierons la compatibilité et préparerons la pièce pour vous.",
    detail_call_now: "Appeler le +216 98 228 469 pour commander",
    detail_visit_shop: "Visiter le magasin à Rue de l'Abreuvoir, Sousse",
  },
  ar: {
    nav_home: "الرئيسية",
    nav_parts: "كتالوج قطع الغيار",
    nav_contact: "اتصال",
    nav_call: "اتصل بنا",
    hero_badge: "أخصائي قطع غيار أوبل وفورد — سوسة",
    hero_title_parts: "قطع الغيار",
    hero_title_prefix: "الأصلية وبأعلى جودة",
    hero_subtitle: "مصدرك المتميز لقطع غيار أوبل وفورد. من مجموعات المحرك والفرامل إلى نظام التعليق والزيوت. جودة ممتازة، أسعار عادلة، وتوجيهات من الخبراء.",
    hero_stat_parts: "قطعة مسجلة",
    hero_stat_models: "طراز سيارات مغطى",
    hero_stat_quality: "فحص الجودة",
    hero_btn_browse: "تصفح كتالوج قطع الغيار",
    hero_btn_contact: "تواصل معنا",
    hero_btn_call: "اتصل بالمركز",
    brand_section_title: "اختر ماركة سيارتك",
    brand_section_subtitle: "اعثر على قطع الغيار المتطابقة تمامًا والمصممة خصيصًا لهيكل طراز سيارتك.",
    brand_opel_desc: "متوافق مع طرازات أوبل أسترا G & H، كورسا C، وفيكترا B.",
    brand_ford_desc: "متوافق مع طرازات فورد فوكس Mk1 & Mk2، فييستا Mk5، ومونديو Mk3.",
    brand_explore_opel: "تصفح كتالوج أوبل ←",
    brand_explore_ford: "تصفح كتالوج فورد ←",
    featured_parts_title: "قطع غيار مميزة متوفرة",
    featured_parts_subtitle: "قطع غيار مطلوبة بشدة متوفرة للاستلام الفوري أو التوصيل في سوسة.",
    featured_btn_all: "تصفح جميع القطع (+100)",
    why_us_title: "لماذا تختار STE SAKJI",
    why_us_subtitle: "ملتزمون بتقديم قطع غيار متميزة، أسعار شفافة، وخدمة ممتازة في سوسة.",
    why_us_01_title: "جودة أصلية",
    why_us_01_desc: "نحن نوفر فقط قطع الغيار الأصلية OEM والمكونات عالية الجودة التي تم اختبارها واعتمادها بالكامل.",
    why_us_02_title: "سهولة الوصول",
    why_us_02_desc: "نحن متواجدون في سوسة (نهج Abreuvoir)، ونوفر الاستلام الفوري أو التوزيع المحلي السريع.",
    why_us_03_title: "نصائح الخبراء",
    why_us_03_desc: "هل تحتاج إلى التحقق من التوافق؟ اتصل بفريقنا للتحقق من توافق القطعة مع رقم شاسيه سيارتك.",
    testimonials_title: "ماذا يقول عملائنا",
    testimonials_subtitle: "آراء صادقة من مالكي أوبل وفورد الذين يشترون قطع الغيار منا.",
    cta_title: "تبحث عن قطعة غيار معينة؟",
    cta_subtitle: "قم بزيارة محلنا في سوسة أو تصفح كتالوجنا للتحقق من توفر القطع.",
    cta_btn_contact: "زيارة محلنا",
    cta_btn_call: "اتصل بـ +216 98 228 469",
    cta_btn_browse: "تصفح الكتالوج",
    footer_tagline: "محل بيع قطع غيار سيارات احترافي لسيارات أوبل وفورد. قطع غيار أصلية OEM في سوسة، تونس.",
    footer_quick_links: "روابط سريعة",
    footer_contact_hours: "الاتصال وأوقات العمل",
    footer_address: "نهج Abreuvoir، سوسة",
    footer_rights: "STE SAKJI AutoShop. جميع الحقوق محفوظة.",
    hours_mon_fri: "الأحد – الخميس:",
    hours_sat: "السبت:",
    hours_sun: "الأحد:",
    hours_closed: "مغلق",
    parts_header_title: "كتالوج قطع الغيار",
    parts_header_subtitle: "تصفح كتالوجنا الشامل الذي يحتوي على أكثر من 100 قطعة غيار أصلية عالية الجودة لطرازات أوبل وفورد.",
    parts_search_placeholder: "ابحث باسم القطعة، رقم OEM، الموديل...",
    parts_filter_brand: "الماركة",
    parts_filter_model: "الموديل",
    parts_filter_category: "الفئة",
    parts_filter_manufacturer: "الشركة المصنعة",
    parts_filter_condition: "الحالة",
    parts_condition_all: "جميع الحالات",
    parts_condition_new: "جديد",
    parts_condition_reconditioned: "مجدد",
    parts_showing: "عرض",
    parts_count_parts: "قطع غيار",
    parts_clear_filters: "مسح التصفية",
    parts_view_details: "عرض التفاصيل",
    parts_price: "السعر",
    parts_stock_status: "حالة المخزون",
    parts_stock_in: "متوفر",
    parts_stock_low: "مخزون منخفض",
    parts_stock_out: "نفذت الكمية",
    parts_empty_title: "لم يتم العثور على قطع تطابق بحثك",
    parts_empty_desc: "حاول إعادة تعيين التصفية أو البحث عن شيء آخر.",
    parts_empty_btn: "إلغاء جميع التصفية",
    parts_brand: "الماركة",
    parts_model: "الموديل",
    parts_category: "الفئة",
    parts_manufacturer: "الشركة المصنعة",
    parts_oem: "رقم OEM",
    parts_year: "نطاق السنوات",
    detail_back: "← العودة إلى الكتالوج",
    detail_compatible_models: "الموديلات المتوافقة",
    detail_specifications: "المواصفات",
    detail_part_number: "رقم القطعة (OEM)",
    detail_brand: "ماركة السيارة",
    detail_condition: "الحالة",
    detail_category: "الفئة",
    detail_manufacturer: "الشركة المصنعة",
    detail_year_range: "نطاق السنوات المتوافق",
    detail_stock_qty: "الكمية المتوفرة",
    detail_unit_price: "سعر الوحدة",
    detail_order_instructions: "كيفية الطلب",
    detail_order_desc: "لطلب هذه القطعة، يرجى زيارة محلنا في سوسة أو التواصل معنا مع إعطائنا رقم القطعة OEM. سنقوم بالتحقق من توافقها مع شاسيه سيارتك وتجهيزها لك.",
    detail_call_now: "اتصل بـ +216 98 228 469 للطلب",
    detail_visit_shop: "زيارة المحل في نهج Abreuvoir، سوسة",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: keyof typeof TRANSLATIONS.en) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(
    (localStorage.getItem('lang') as Language) || 'en'
  );

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('lang', lang);
  };

  useEffect(() => {
    // Handle RTL dynamically based on language
    if (language === 'ar') {
      document.documentElement.dir = 'rtl';
      document.documentElement.lang = 'ar';
    } else {
      document.documentElement.dir = 'ltr';
      document.documentElement.lang = language;
    }
  }, [language]);

  const t = (key: keyof typeof TRANSLATIONS.en): string => {
    return TRANSLATIONS[language][key] || TRANSLATIONS.en[key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
